### ISSUE TITLE
Beta Bugs

### ISSUE THREAD

**Issue by bhellar** [obble/modui_classic#7] opened 2019-08-16 12:54 UTC
Greetings Obble,

I've discovered 2 bugs while using your UI in the closed beta this week:

1. Stance Bar Fixed Position
The stance bar (or special action bar, not sure exactly what its called) is being set in a fixed position assuming the user has enabled all 3 action bars. With only 1 or 2 action bars enabled the stance bar is not aligned with the actionbar UI, and looks like its floating in space. See my screenshot below:

![WoWScrnShot_081319_223244](https://user-images.githubusercontent.com/2537484/63168312-cdb1e980-c001-11e9-8ce5-0c7d80fa58d7.jpg)

2. Buff / Debuff Auras

I've run into a couple of issues with buff / debuff implementation. First, debuff auras are not displaying for me. They do appear correctly for the target unitframe, but not in the main upper right area of the UI.  I was in beta and got one of the annoying 10min disease debuffs and noticed nothing was displayed until I clicked on myself and saw it in the target unit frame.  I was able to workaround this by disabling the Aura module.  I've also noticed some inconsistencies with poisons on rogue weapons not appearing, but haven't been able yet to reproduce. 

Thanks for taking the time and porting this UI over to classic, I love the simplicity and feel of this UI in classic.

**Comment by obble** [comment] 2019-08-16 21:06
Hey, thanks for the report.

1. I've a potential solution for this already but unfortunately now unable to test until release day - i'll have it up as soon as I can then though.

2. Did i... not get a debuff in the stress test? Or just totally failed to notice it? Either way, yikes! Thanks for the report - it looks like the debuffs were being parented to a frame which doesn't exist in the classic variant of the game, so they silently fail to show up. I'll push a fix for this in the next couple of days as it shouldn't really need any testing.

Let me know any more details about poisons if you can figure out what's causing problems. I haven't spent too much time looking over class specific details yet as I wanted to focus on getting the fundamentals painted in over those few stress test days.

I'll probably add a specific secondary option to toggle the customised debuff layout off too (but leave the overall aura styling for modui on) pre-release, as they're laid out a little differently for my taste for increased visibility in PvP - a vertical list with big name titles for easy understanding of debuff effects.

**Comment by Starcheck** [comment] 2019-08-23 14:37
Hey,

Love the idea of this being reworked in classic!

I have some weird issues with it. If I download modui and copy/rename it as described the following happend during Stress Test and PTR build 1.13.2:

![WoWScrnShot_082319_163209](https://user-images.githubusercontent.com/54445661/63600599-29f9a800-c5c4-11e9-872e-e9fe19141901.jpg)


As you can see both Menu buttons are out of place and the "M" menu is completly gone. There are no other add ons active and I play in Windows client 1920x1080.

Any help to fix is appreciated!

**Comment by obble** [comment] 2019-08-23 21:45
Hey there, was/is this the latest version of modui from over the stress test weekend? 

This screenshot looks similar to how i vaguely remember first logging in to the stress test before starting to fix things up that had been written without the ability to start testing. You may need to update your version for these fixes.

If it is the most recent version and you still have access to the beta, can you run this command in chat _/console scriptErrors 1_, reload the UI and let me know if any errors appear?

**Comment by Starcheck** [comment] 2019-08-24 08:23
Hey, thanks for your reply!

this is the latest version of ModUi provided. The screenshot was made yesterday on a 1.13.2.31446 PTR provided by Arctium.io. It is an empty Sandbox.
The same issue was present during the whole last Stress Test and I updated modUI everytime you released another version. I cleared WTF and Interface to make sure nothing else is messing it up, still same issue.
Unfortunatly Blizzard updated to 1.13.2.31650 today, so the sandbox isnt working anymore and I cannot try your command. But I will do so on launch!

Thanks again for your work, I am very looking forward to it!

**Comment by obble** [comment] 2019-08-24 09:20
Dang I wish I knew about that sandbox earlier!

Anyway yeah - let me know how it goes on launch with error reports enabled, theres a chance the issue is something obvious that I didn’t recognise in a small test window - an issue caused by a certain class or something like that.

**Comment by obble** [comment] 2019-08-27 08:19
This should be fixed now, plz reopen if any issues persist.

**Closed by obble** 2019-08-27 08:19 UTC
