### ISSUE TITLE
NEED FOCUS FRAME

### ISSUE THREAD

**Issue by rc4p** [obble/modui_classic#54] opened 2019-09-04 05:56 UTC

**Comment by obble** [comment] 2019-09-04 07:23
yes

**Comment by baruchvlz** [comment] 2019-09-04 14:16
I don't think focus frames is possible in Classic. You can read the README on this repository: https://github.com/wardz/FocusFrame

**Comment by obble** [comment] 2019-09-04 14:30
Ah, that's a shame - I was kind of hoping they'd left open the possibility with a 'focus' unitid with the client ported from retail. It looks like libraries like oUF have also dropped support for it.

How do you see the nameplate idea working? I could see it if unitids for nameplates weren't dropped at a range of 20-30yards

**Comment by baruchvlz** [comment] 2019-09-04 15:32
Sorry I meant to say UnitFrames not nameplates. You could possibly add an extra option to the UnitFrame "Focus" (as it is in retail). Will have to store the UnitID so you can keep track of health, buffs, debuffs, power, etc.

**Comment by Xaero252** [comment] 2019-09-04 18:38
> Sorry I meant to say UnitFrames not nameplates. You could possibly add an extra option to the UnitFrame "Focus" (as it is in retail). Will have to store the UnitID so you can keep track of health, buffs, debuffs, power, etc.
> 
> But then again, if libraries like uOF and FocusFrame (which was amazing in pvt servers) are dropping support, then the overhead work might be too much.

The problem is there isn't a way to grab or use this information in combat without causing taint thanks to the new lua sandbox.

This is something Blizzard needs to address as they have frankly broken part of the vanilla experience.

**Comment by obble** [comment] 2019-09-04 18:42
i mean, having a focus frame wasn't part of the vanilla experience d:

i'm going to close this for now, it seems unlikely i'll be adding this in the near future with the current systems in place

**Closed by obble** 2019-09-04 18:42 UTC

**Comment by Xaero252** [comment] 2019-09-05 00:47
Addons that literally played the game for you were part of the vanilla experience though ;-)
